name: questkeeper
description: "The gamified task tracker"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.8.3+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flex_color_picker: ^3.7.0
  url_launcher: ^6.3.1
  supabase: ^2.6.2
  supabase_flutter: ^2.8.3
  supabase_auth_ui: ^0.5.4
  home_widget: ^0.7.0
  shared_preferences: ^2.3.5
  flutter_lucide: ^1.6.1
  riverpod_generator: ^2.6.3
  rename_app: ^1.6.1
  email_validator: ^2.1.17
  sentry_flutter: ^8.12.0
  feedback_sentry: ^3.1.0
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  http: ^1.2.2
  flame: ^1.23.0
  flame_tiled: ^1.21.2
  flame_riverpod: ^5.4.7
  flutter_cache_manager: ^3.4.1
  faker: ^2.2.0
  uuid: ^4.5.1
  dice_bear: ^0.1.7
  skeletonizer: ^1.4.2
  dynamic_color: ^1.7.0
  flutter_svg: ^2.0.16
  toastification: ^2.3.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  showcaseview: ^3.0.0
  dio: ^5.7.0
  dio_http2_adapter: ^2.5.3
  sentry_dio: ^8.12.0
  numberpicker: ^2.1.2
  posthog_flutter: ^4.9.0
  connectivity_plus: ^6.1.1
  introduction_screen: ^3.1.14
  lottie: ^3.3.0
  dotlottie_loader: ^0.0.4
  rive: ^0.13.20
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  json_serializable: ^6.9.0
  msix: ^3.16.8

dependency_overrides:
  shared_preferences_android: ^2.3.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/backgrounds/
    - assets/images/backgrounds/living_room/
    - assets/images/backgrounds/office/
    - assets/images/backgrounds/school/
    - assets/images/characters/
    - assets/images/characters/red_panda/
    - assets/images/characters/pidgeon/
    - assets/images/characters/ferret/
    - assets/tiles/
    - assets/trophy/
    - assets/lottie/
    - assets/rive/
