name: questkeeper
description: "A fun way to track your tasks"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.7.4+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flex_color_picker: ^3.6.0
  url_launcher: ^6.3.1
  supabase: ^2.6.0
  supabase_flutter: ^2.8.1
  supabase_auth_ui: ^0.5.4
  home_widget: ^0.7.0
  shared_preferences: ^2.3.3
  flutter_lucide: ^1.6.0
  riverpod_generator: ^2.6.3
  rename_app: ^1.6.1
  email_validator: ^2.1.17
  sentry_flutter: ^8.10.1
  feedback_sentry: ^3.1.0
  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  http: ^1.2.2
  flame: ^1.22.0
  flame_tiled: ^1.21.1
  cached_network_image: ^3.4.1
  flame_riverpod: ^5.4.6
  flutter_cache_manager: ^3.4.1
  faker: ^2.2.0
  uuid: ^4.5.1
  dice_bear: ^0.1.7
  skeletonizer: ^1.4.2
  dynamic_color: ^1.7.0
  flutter_svg: ^2.0.16
  mixpanel_flutter: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  json_serializable: ^6.9.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/tiles/
    - assets/trophy/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
