name: questkeeper
description: "A fun way to track your tasks"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.7.0+3

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  flex_color_picker: ^3.5.1
  url_launcher: ^6.3.0
  supabase: ^2.3.0
  supabase_flutter: ^2.6.0
  supabase_auth_ui: ^0.5.1
  home_widget: ^0.7.0
  shared_preferences: ^2.3.2
  flutter_lucide: ^1.4.0
  riverpod_generator: ^2.4.3
  rename_app: ^1.6.1
  email_validator: ^2.1.17
  sentry_flutter: ^8.9.0
  feedback_sentry: ^3.0.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  http: ^1.2.2
  flame: ^1.19.0
  flame_tiled: ^1.20.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  json_serializable: ^6.8.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/tiles/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
