// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDl3gLf4TqQ3M7VRCi95at_DjP-Ei1Q0',
    appId: '1:479691835174:ios:a6fddf000f1cd2c33763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    storageBucket: 'assigngo-d890c.appspot.com',
    iosBundleId: 'app.questkeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARDl3gLf4TqQ3M7VRCi95at_DjP-Ei1Q0',
    appId: '1:479691835174:ios:c0d4ddc476aaa1e13763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    storageBucket: 'assigngo-d890c.appspot.com',
    iosBundleId: 'app.questkeeper.macos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEoFGpjPeK5xK53akStqUmTuIYuj6Y_VY',
    appId: '1:479691835174:web:a47b44273e5f9ae23763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    authDomain: 'assigngo-d890c.firebaseapp.com',
    storageBucket: 'assigngo-d890c.appspot.com',
    measurementId: 'G-RG7VWPHH79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA71mAfcb4HlBkKnpcXSGTsDRixQ7YLa3k',
    appId: '1:479691835174:android:6777d673619a007c3763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    storageBucket: 'assigngo-d890c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEoFGpjPeK5xK53akStqUmTuIYuj6Y_VY',
    appId: '1:479691835174:web:b489bf676a41a1a33763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    authDomain: 'assigngo-d890c.firebaseapp.com',
    storageBucket: 'assigngo-d890c.appspot.com',
    measurementId: 'G-S5TFLWYEJ9',
  );

}