// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEoFGpjPeK5xK53akStqUmTuIYuj6Y_VY',
    appId: '1:479691835174:web:daa0e390776cd9d93763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    authDomain: 'assigngo-d890c.firebaseapp.com',
    storageBucket: 'assigngo-d890c.appspot.com',
    measurementId: 'G-L4EHMBMZTG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDl3gLf4TqQ3M7VRCi95at_DjP-Ei1Q0',
    appId: '1:479691835174:ios:edd9efaa419ca31d3763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    storageBucket: 'assigngo-d890c.appspot.com',
    iosBundleId: 'dev.ishanmisra.assigngo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARDl3gLf4TqQ3M7VRCi95at_DjP-Ei1Q0',
    appId: '1:479691835174:ios:538d86ccbdb48d703763e7',
    messagingSenderId: '479691835174',
    projectId: 'assigngo-d890c',
    storageBucket: 'assigngo-d890c.appspot.com',
    iosBundleId: 'com.example.assigngoRewrite',
  );

}