name: Flutter Desktop Deployment

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build artifacts
        run: dart run msix:create -d "AssignGo" -i "IshanMisra.AssignGo" --split-debug-info=./debug-info --obfuscate --release
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: local_api_server-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: build/windows/runner/Release/local_api_server-${{github.ref_name}}-windows.zip

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build artifacts
        run: flutter build macos --split-debug-info=./debug-info --obfuscate --release
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: local_api_server-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release
      - name: Release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          files: build/macos/Build/Products/Release/local_api_server-${{github.ref_name}}-macos.zip
